### ISSUE TITLE
Counting sometimes thinks a number is wrong when it's right

### ISSUE THREAD

**Issue by nyakase** [VukkyLtd/VukkyBot#48] opened 2020-12-08 10:41 UTC
we have absolutely no idea why this happens
![image](https://user-images.githubusercontent.com/46850780/101479727-f5456780-3952-11eb-9a41-0c2f7130c4d2.png)

**Comment by emilianya** [comment] 2020-12-08 11:20
It even says afterwards that correct number was the number said

**Comment by jakoinc134** [comment] 2020-12-08 19:18
bot broke!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by emilianya** [comment] 2020-12-08 19:20
@jakoinc134 yes. we know. that is what the issue is.

**Comment by emilianya** [comment] 2020-12-09 05:47
bumping up priority because it seems to be getting more and more common

**Comment by emilianya** [comment] 2020-12-09 05:51
I think I might know what is happening here! Applying a fix asap

**Comment by emilianya** [comment] 2020-12-09 05:58
#49 should fix this

**Comment by emilianya** [comment] 2020-12-09 06:08
https://imgur.com/a/7RCVJs3

**Comment by emilianya** [comment] 2020-12-09 07:08
Seems to have been fixed with the pull req

**Closed as completed** 2020-12-09 07:08 UTC
Labels: bug, priority: quite important
